declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_IMQA_COLLECTOR_URL?: string;
    NEXT_PUBLIC_IMQA_SERVICE_NAME?: string;
    NEXT_PUBLIC_IMQA_SERVICE_VERSION?: string;
    NEXT_PUBLIC_IMQA_SERVICE_KEY?: string;
    NEXT_PUBLIC_IMQA_SERVICE_NAMESPACE?: string;
    NEXT_PUBLIC_IMQA_DEPLOYMENT_ENVIRONMENT?: string;
    NEXT_PUBLIC_IMQA_DEBUG?: string;
    NEXT_PUBLIC_IMQA_SAMPLING_PROBABILITY?: string;
    NEXT_PUBLIC_IMQA_CONSOLE_CAPTURE?: string;
    NEXT_PUBLIC_IMQA_ADVANCED_NETWORK_CAPTURE?: string;
    NEXT_PUBLIC_IMQA_DISABLE_REPLAY?: string;
    NEXT_PUBLIC_IMQA_CAPTURE_METRICS?: string;
  }
}
